name: kitaura
description: AI-powered CV and proposal builder
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # STATE MANAGEMENT
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # NAVIGATION
  go_router: ^17.2.3

  # FIREBASE
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0
  cloud_functions: ^6.3.1


  # HTTP
  dio: ^5.9.2

  # EDITOR
  flutter_quill: ^11.5.0

  # PDF
  pdf: ^3.12.0
  printing: ^5.14.3

  # FILE
  file_picker: ^11.0.2

  # IMAGE
  cached_network_image: ^3.4.1

  # COLOR
  flutter_colorpicker: ^1.1.0

  # RESPONSIVE
  flutter_screenutil: ^5.9.3

  # ANIMATIONS
  flutter_animate: ^4.5.2

  # LOCAL STORAGE
  shared_preferences: ^2.5.5

  # PAYMENTS
  flutter_stripe: ^12.6.0

  # TOAST
  toastification: ^3.2.0

  # ICONS
  lucide_icons: ^0.257.0

  # LOADING
  shimmer: ^3.0.0
  skeletonizer: ^2.1.3

  # UTILITIES
  uuid: ^4.5.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  web: ^1.1.1
  vector_math: ^2.1.4
  showcaseview: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/cv_templates/
    - assets/cl_templates/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf
    - family: Sekuya
      fonts:
        - asset: assets/fonts/Sekuya.ttf