// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1BLEz0a7XziR8KfV50ZvLqDqjk9mPK-4',
    appId: '1:230575893042:web:3a96ee2dd3277f4206aa2b',
    messagingSenderId: '230575893042',
    projectId: 'kitaura-app',
    authDomain: 'kitaura-app.firebaseapp.com',
    storageBucket: 'kitaura-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQA502Y5bz2c_A1zADeyGabH_NHFRnlGM',
    appId: '1:230575893042:android:7f2e5fe135b61be806aa2b',
    messagingSenderId: '230575893042',
    projectId: 'kitaura-app',
    storageBucket: 'kitaura-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUhlNuXeP5YHtfhgO6fFoaYresvYNFg4',
    appId: '1:230575893042:ios:64773c9d25914cf106aa2b',
    messagingSenderId: '230575893042',
    projectId: 'kitaura-app',
    storageBucket: 'kitaura-app.firebasestorage.app',
    iosClientId: '230575893042-hsn18u3rf1codgb5pb1hoad0uo5tb42u.apps.googleusercontent.com',
    iosBundleId: 'kitaura.winibex.com.kitaura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1BLEz0a7XziR8KfV50ZvLqDqjk9mPK-4',
    appId: '1:230575893042:web:a06289d4eec1c30c06aa2b',
    messagingSenderId: '230575893042',
    projectId: 'kitaura-app',
    authDomain: 'kitaura-app.firebaseapp.com',
    storageBucket: 'kitaura-app.firebasestorage.app',
  );
}
