// lib/shared/models/announcement_model.dart
//
// Mirrors config/announcement in Firestore. The `id` field is
// auto-generated by adminUpdateAnnouncement on every save; the main app
// compares it against users/{uid}.lastSeenAnnouncementId to decide
// whether to show the banner.

class AnnouncementModel {
  final String? id;
  final bool active;
  final String title;
  final String body;
  final String severity; // 'info' | 'warn' | 'critical'
  final String? linkUrl;
  final String? linkLabel;

  const AnnouncementModel({
    required this.id,
    required this.active,
    required this.title,
    required this.body,
    required this.severity,
    required this.linkUrl,
    required this.linkLabel,
  });

  factory AnnouncementModel.fromMap(Map<String, dynamic> map) {
    return AnnouncementModel(
      id: map['id'] as String?,
      active: (map['active'] as bool?) ?? false,
      title: (map['title'] as String?) ?? '',
      body: (map['body'] as String?) ?? '',
      severity: (map['severity'] as String?) ?? 'info',
      linkUrl: map['linkUrl'] as String?,
      linkLabel: map['linkLabel'] as String?,
    );
  }

  /// True only when there is an active announcement WITH an id.
  /// (Legacy docs written before the id migration will fail this and
  /// be treated as no-announcement — safe default.)
  bool get isDisplayable => active && id != null && id!.isNotEmpty;
}