// lib/shared/models/canvas_item.dart
//
// Canvas item data + snapshot classes for undo/redo.
// CHANGES FROM PREVIOUS VERSION:
//   1. ItemSnapshot now stores deltaJson (Quill delta) for text undo/redo
//   2. imageBytes stored in snapshot for image undo/redo

import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:kitaura/shared/models/table_data.dart';
import 'canvas_item_type.dart';
import 'section_type.dart';

// ─── CANVAS ITEM MODEL ───────────────────────────────────────────────────

class CanvasItem {
  final String id;
  CanvasItemType type;
  Offset position;
  double width, height, rotation, borderWidth;
  Color color, borderColor;
  Uint8List? imageBytes;
  IconData? iconData;
  String title;
  String? role;   // 'hero' | 'heading' | 'underline' | null (flowing content)
  String? group;  // pairs a heading with its underline, e.g. 'execSummary'
  bool flipX, flipY;

  /// Set by the reflow engine when this text section overflows a page and
  /// must continue onto the next. Holds the leftover delta ops that didn't
  /// fit. Null = no split needed. Rebuilt fresh on every reflow.
  List<Map<String, dynamic>>? overflowOps;
  double overflowY = 0; // Y position where the continuation should render
  /// True if this item is a temporary continuation piece generated by the
  /// reflow engine to render overflow text. Never saved; rebuilt each reflow.
  bool isContinuation = false;

  /// What kind of CV section this is (for AI autofill). Only meaningful
  /// for textSection items. Auto-detected from title if not provided.
  SectionType sectionType;

  QuillController? controller;
  FocusNode? focusNode;
  ScrollController? scrollController;

  TableData? tableData;

  CanvasItem({
    required this.type,
    required this.position,
    required this.width,
    required this.height,
    this.rotation = 0,
    this.color = Colors.transparent,
    this.borderColor = Colors.grey,
    this.borderWidth = 1,
    this.imageBytes,
    this.iconData,
    this.title = '',
    this.role,
    this.group,
    this.flipX = false,
    this.flipY = false,
    SectionType? sectionType,
    TableData? tableData,
  })  : id = UniqueKey().toString(),
        sectionType = sectionType ??
            (type == CanvasItemType.textSection
                ? SectionType.detectFromTitle(title)
                : SectionType.custom) {
    if (type == CanvasItemType.textSection) {
      controller = QuillController.basic();
      focusNode = FocusNode();
      scrollController = ScrollController();
    }
    if (type == CanvasItemType.tableSection) {
      this.tableData = tableData ?? TableData.empty();
    }
  }

  bool get isText => type == CanvasItemType.textSection;

  bool get isTable => type == CanvasItemType.tableSection;

  void dispose() {
    controller?.dispose();
    focusNode?.dispose();
    scrollController?.dispose();
  }
}

// ─── SNAPSHOT (for undo/redo) ────────────────────────────────────────────
//
// NOW STORES:
//   - deltaJson: full Quill delta for text sections (enables text undo)
//   - imageBytes: image data (enables image undo)

class ItemSnapshot {
  final String id;
  final CanvasItemType type;
  final Offset position;
  final double width, height, rotation, borderWidth;
  final Color color, borderColor;
  final IconData? iconData;
  final String title;
  final bool flipX, flipY;
  final SectionType sectionType;
  final List<dynamic>? deltaJson;   // NEW — Quill delta for text undo
  final Uint8List? imageBytes;      // NEW — image data for undo
  final Map<String, dynamic>? tableDataJson;

  ItemSnapshot({
    required this.id,
    required this.type,
    required this.position,
    required this.width,
    required this.height,
    required this.rotation,
    required this.borderWidth,
    required this.color,
    required this.borderColor,
    required this.iconData,
    required this.title,
    required this.flipX,
    required this.flipY,
    required this.sectionType,
    this.deltaJson,
    this.imageBytes,
    this.tableDataJson,

  });

  factory ItemSnapshot.from(CanvasItem item) => ItemSnapshot(
    id: item.id,
    type: item.type,
    position: item.position,
    width: item.width,
    height: item.height,
    rotation: item.rotation,
    borderWidth: item.borderWidth,
    color: item.color,
    borderColor: item.borderColor,
    iconData: item.iconData,
    title: item.title,
    flipX: item.flipX,
    flipY: item.flipY,
    sectionType: item.sectionType,
    // Capture text content for undo/redo
    deltaJson: item.isText && item.controller != null
        ? item.controller!.document.toDelta().toJson()
        : null,
    // Capture image data for undo/redo
    imageBytes: item.imageBytes != null
        ? Uint8List.fromList(item.imageBytes!)
        : null,
    tableDataJson: item.isTable && item.tableData != null
        ? item.tableData!.toJson()
        : null,
  );
}

class CanvasSnapshot {
  final List<ItemSnapshot> items;
  final String? selectedId;
  final Color canvasBackground;

  CanvasSnapshot(this.items, this.selectedId, this.canvasBackground);
}