// lib/shared/models/section_type.dart
//
// Section types for both CVs AND cover letters.
// NEW: senderAddress, recipientAddress, dateLine, salutation,
//      coverLetterBody, closing, signature

enum SectionType {
  // CV section types
  name,
  jobTitle,
  contact,
  summary,
  experience,
  education,
  skills,
  projects,
  certifications,
  awards,
  languages,
  interests,
  volunteer,
  references,
  hobbies,
  socialLinks,

  // Cover letter section types
  senderAddress,
  recipientAddress,
  dateLine,
  salutation,
  coverLetterBody,
  closing,
  signature,

  custom;

  String get label {
    switch (this) {
      case SectionType.name:
        return 'Full Name';
      case SectionType.jobTitle:
        return 'Job Title';
      case SectionType.contact:
        return 'Contact Info';
      case SectionType.summary:
        return 'Summary / Profile';
      case SectionType.experience:
        return 'Work Experience';
      case SectionType.education:
        return 'Education';
      case SectionType.skills:
        return 'Skills';
      case SectionType.projects:
        return 'Projects';
      case SectionType.certifications:
        return 'Certifications';
      case SectionType.awards:
        return 'Awards / Honors';
      case SectionType.languages:
        return 'Languages';
      case SectionType.interests:
        return 'Interests';
      case SectionType.volunteer:
        return 'Volunteer Experience';
      case SectionType.references:
        return 'References';
      case SectionType.hobbies:
        return 'Hobbies';
      case SectionType.socialLinks:
        return 'Social Links';
      case SectionType.senderAddress:
        return 'Sender Address';
      case SectionType.recipientAddress:
        return 'Recipient Address';
      case SectionType.dateLine:
        return 'Date';
      case SectionType.salutation:
        return 'Salutation';
      case SectionType.coverLetterBody:
        return 'Letter Body';
      case SectionType.closing:
        return 'Closing';
      case SectionType.signature:
        return 'Signature';
      case SectionType.custom:
        return 'Custom';
    }
  }

  bool get isAutofillable {
    switch (this) {
      case SectionType.custom:
      case SectionType
          .coverLetterBody: // Body is generated by AI, not autofilled
        return false;
      default:
        return true;
    }
  }

  String get key => toString().split('.').last;

  static SectionType fromKey(String key) {
    return SectionType.values.firstWhere(
      (t) => t.key == key,
      orElse: () => SectionType.custom,
    );
  }

  static SectionType detectFromTitle(String title) {
    final t = title.toLowerCase().trim();

    // Cover letter specific (check first, more specific patterns)
    if (t.contains('salutation') || t.startsWith('dear')) {
      return SectionType.salutation;
    }
    if (t.contains('sender') && t.contains('address')) {
      return SectionType.senderAddress;
    }
    if (t.contains('recipient') ||
        t.contains('hiring manager') ||
        (t.contains('company') && t.contains('address'))) {
      return SectionType.recipientAddress;
    }
    if (t == 'date' || t.contains('date line')) return SectionType.dateLine;
    if (t.contains('body') ||
        t.contains('letter body') ||
        t.contains('main letter')) {
      return SectionType.coverLetterBody;
    }
    if (t.contains('closing') ||
        t.contains('sincerely') ||
        t.contains('regards')) {
      return SectionType.closing;
    }
    if (t.contains('signature') || t.contains('sign-off')) {
      return SectionType.signature;
    }

    // CV detection
    if (t.contains('name') || t.contains('full name')) return SectionType.name;
    if (t.contains('job title') ||
        t.contains('role') ||
        t.contains('position') ||
        t.contains('designation')) {
      return SectionType.jobTitle;
    }
    if (t.contains('contact') ||
        t.contains('email') ||
        t.contains('phone') ||
        t.contains('address')) {
      return SectionType.contact;
    }
    if (t.contains('summary') ||
        t.contains('profile') ||
        t.contains('objective') ||
        t.contains('about')) {
      return SectionType.summary;
    }
    if (t.contains('experience') ||
        t.contains('work') ||
        t.contains('employment') ||
        t.contains('career')) {
      return SectionType.experience;
    }
    if (t.contains('education') ||
        t.contains('academic') ||
        t.contains('qualification') ||
        t.contains('degree')) {
      return SectionType.education;
    }
    if (t.contains('skill') ||
        t.contains('competenc') ||
        t.contains('technical') ||
        t.contains('expertise')) {
      return SectionType.skills;
    }
    if (t.contains('project')) return SectionType.projects;
    if (t.contains('certif') ||
        t.contains('license') ||
        t.contains('accreditation')) {
      return SectionType.certifications;
    }
    if (t.contains('award') ||
        t.contains('honor') ||
        t.contains('achievement') ||
        t.contains('recognition')) {
      return SectionType.awards;
    }
    if (t.contains('language')) return SectionType.languages;
    if (t.contains('interest') || t.contains('hobby') || t.contains('hobbies')) {
      return SectionType.hobbies;
    }
    if (t.contains('volunteer') ||
        t.contains('community') ||
        t.contains('non-profit')) {
      return SectionType.volunteer;
    }
    if (t.contains('reference')) return SectionType.references;
    if (t.contains('social') ||
        t.contains('github') ||
        t.contains('twitter') ||
        t.contains('portfolio')) {
      return SectionType.socialLinks;
    }

    return SectionType.custom;
  }
}
